name: Go Test Suite

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run Tests
        run: go test -v ./...

      - name: Coverage
        run: go test -coverprofile=coverage.txt
